apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pingpong-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                - env: qa
                - env: preprod
                - env: prod
          - list:
              elements:
                - service: ping
                - service: pong
  template:
    metadata:
      name: '{service}-{env}'
      labels:
        app.kubernetes.io/part-of: pingpong
        app.kubernetes.io/managed-by: argocd-appset
        app.kubernetes.io/component: application
        env: '{env}'
        service: '{service}'
    spec:
      project: pingpong
      source:
        repoURL: https://github.com/daoquocquyen/pingpong-config.git
        targetRevision: main
        path: '{service}/overlays/{env}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{service}-{env}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      revisionHistoryLimit: 10
