apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: pong
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
